# site name
prefixName:  Blog # さくら荘その
siteName: 胡莱峦镐
# favicon and site master avatar
favicon: http://82.156.182.226:8099/favicon.ico
avatar: /Avatar/avatar.jpg
url: http://82.156.182.226
description: The Winner Takes It All
cdn: http://82.156.182.226:8099
pjax: 1
# 1开启
mathjax: 0

# 公告
notice: 网站正在逐步建设完全中。另：封面来自May爷群友的分享，侵删
lazyloadImg: http://82.156.182.226:8099/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    UE4: {path: /categories/UE4/, fa:  }, 
    Unity: {path: /categories/Unity/, fa:  }, 
    图形学: {path: /categories/图形学/, fa:  },
    杂记: {path: /categories/杂记/, fa:  }, 
    转载: {path: /categories/转载/, fa:  }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - http://82.156.182.226:8099/Cover/c2.jpg #1
  - http://82.156.182.226:8099/Cover/c3.jpg #2
   #3
  - http://82.156.182.226:8099/Cover/c5.jpg #4
   #5
  - http://82.156.182.226:8099/Cover/c7.jpg #6
  - http://82.156.182.226:8099/Cover/c8.jpg #7
  # - http://82.156.182.226:8099/Cover/c9.jpg #8

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  # - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: https://github.com/Videa-Lab-JLU, title: Videa Lab, desc: Videa Lab · Jilin University, img: /img/startdash/Videa1.png}
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}



# your site build time or founded date
siteBuildingTime: 04/17/2021

#social  url, img PC端配置
social:
  github: {url: http://github.com/songjihu, img: /icon/github.svg}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: http://music.163.com/m/user/home?id=120362485, img: /icon/网易云音乐(1).svg}
  # zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: mailto:275245802@qq.com, img: /icon/QQ邮箱.svg}
  wechat: {url: /#, qrcode: /img/custom/QQ图片20210430082716.jpg, img: /icon/微信.svg}
  wechat2: {url: /#, qrcode: /img/custom/QQ图片20210430082838.jpg, img: /icon/QQ.svg}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/songjihu, fa: fa-github, color: 333}
  # : {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  # qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: # https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.png
  wechat: /img/custom/donate/WeChanQR.png
  wechatSQ: /img/custom/donate/WeChanSQ.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: # https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: # Unbroken.mp4

aplayer: 
  id: 6659011864
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: KypqgrkEt3w7iFwjG2xNSi0P-gzGzoHsz
v_appKey: 0WdJ7Ru9vPt76HrSGYE21RM4
